### PR TITLE
Small fixes in callbacks

### LINKED ISSUE #169: Benders implementation with callbacks
Hello
I tried to use callbacks on a dummy benders decomposition example (see [here](https://jump.dev/JuMP.jl/stable/tutorials/algorithms/benders_decomposition/) ) but it seems the callback is not called. Any hints to make it working ? 
```Julia
using JuMP
import GLPK
import Xpress



c_1 = [1, 4];
c_2 = [2, 3];
dim_x = length(c_1);
dim_y = length(c_2);
b = [-2; -3];
A_1 = [1 -3; -1 -3];
A_2 = [1 -2; -1 -1];
M = -1000;

MAXIMUM_ITERATIONS = 100;
ABSOLUTE_OPTIMALITY_GAP = 1e-6;

MY_OPTIMIZER = Xpress.Optimizer;

function print_iteration(k, args...)
    f(x) = Printf.@sprintf("%12.4e", x)
    println(lpad(k, 9), " ", join(f.(args), " "))
    return
end

function solve_subproblem(x)
    model = Model(MY_OPTIMIZER)
    set_optimizer_attribute(model, "PRESOLVE", 0);
    @variable(model, y[1:dim_y] >= 0)
    con = @constraint(model, A_2 * y .<= b - A_1 * x)
    @objective(model, Min, c_2' * y)
    optimize!(model)
    @assert termination_status(model) == OPTIMAL
    return (obj = objective_value(model), y = value.(y), π = dual.(con))
end

"""
    my_callback(cb_data)

A callback that implements Benders decomposition. Note how similar it is to the
inner loop of the iterative method.
"""
function my_callback(cb_data)
    global k += 1
    println("calling my_callback")
    x_k = callback_value.(cb_data, x)
    θ_k = callback_value(cb_data, θ)
    lower_bound = c_1' * x_k + θ_k
    ret = solve_subproblem(x_k)
    upper_bound = c_1' * x_k + c_2' * ret.y
    gap = (upper_bound - lower_bound) / upper_bound
    print_iteration(k, lower_bound, upper_bound, gap)
    if gap < ABSOLUTE_OPTIMALITY_GAP
        println("Terminating with the optimal solution")
        return
    end
    cut = @build_constraint(θ >= ret.obj + -ret.π' * A_1 * (x .- x_k))
    MOI.submit(model, MOI.LazyConstraint(cb_data), cut)
    return
end

lazy_model = Model(MY_OPTIMIZER)

set_optimizer_attribute(lazy_model, "PRESOLVE", 0);
@variable(lazy_model, x[1:dim_x] >= 0, Int)
@variable(lazy_model, θ >= M)
@objective(lazy_model, Min, θ)
print(lazy_model)
k = 0

MOI.set(lazy_model, MOI.LazyConstraintCallback(), my_callback)

optimize!(lazy_model)
x_optimal = value.(x)
```

### PR DESCRIPTION
**Pull request by rafabench**
Close #169

### CODE REVIEW

File: src/xprs_callbacks.jl [hunk 1]
```diff
@@ -4,6 +4,9 @@ mutable struct CallbackData
     data::Any # data for user
     model::XpressProblem # local model # ptr_model::Ptr{Nothing}
 end
+Base.cconvert(::Type{Ptr{Cvoid}}, x::CallbackData) = x
+Base.unsafe_convert(::Type{Ptr{Cvoid}}, x::CallbackData) = x.ptr::Ptr{Cvoid}
```
Comment (odow) [inline src/xprs_callbacks.jl:8]: I don't think this is right. `x.ptr` doesn't exist.

Comment (rafabench) [reply src/xprs_callbacks.jl:8]: No it isn't. It should be
```julia
Base.unsafe_convert(::Type{Ptr{Cvoid}}, x::CallbackData) = x.model.ptr::Ptr{Cvoid}
```
But I think these lines aren't used in the code, so we could just remove them.

Comment (odow) [reply src/xprs_callbacks.jl]: Yeah just remove them

**Review by guilhermebodin — APPROVED** [review]
