### PR TITLE
Bug Fix with Problem being returned in pre-solve state

### LINKED ISSUE #133: Xpress returns pre-solve problem when MAXTIME is reached
Hi guys,
I'm experiencing this issue where if the solver reaches the MAXTIME passed by the user, Xpress returns the problem in its pre-solved state and if I try to change the RHS of a constraint using ParameterJuMP it throws this error 
```
XpressError(32): Subroutine not completed successfully, possibly due to invalid argument. Unable to call `Xpress.chgrhs`:
402 Error: Invalid row number passed to XPRSchgrhs.
```
Seems like this is default behavior of Xpress, and we need to use  ` XPRSpostsolve` function  to get back the original
problem.  Any help on this is appreciated.
Found a similar issue raised in the Xpress forums [here.](https://community.fico.com/s/question/0D52E000064qY46SAE/after-solving-a-mip-with-an-early-termination-condition-on-time-maxtime-i-change-the-rhs-of-a-set-of-constraints-and-get-the-following-error-solvererror-402-error-invalid-row-number-passed-to-xprschgrhs) 

EDIT : Adding a MWE for anyone who wants to replicate the issue 
```julia
using JuMP, Xpress, PowerSimulations, PowerSystems, PowerSystemCaseBuilder, InfrastructureSystems
const PSI = PowerSimulations
const PSY = PowerSystems
const PSB = PowerSystemCaseBuilder

test_sys = PSB.build_system(PSITestSystems, "modified_RTS_GMLC_DA_sys");
template = template_unit_commitment(network=CopperPlatePowerModel);

solver = JuMP.optimizer_with_attributes(Xpress.Optimizer, "MIPRELSTOP" => 1e-5, "MAXTIME" => 15)
UC = OperationsProblem(
    template,
    test_sys;
    optimizer = solver,
    optimizer_log_print = true,
    balance_slack_variables = true,
)


problems = SimulationProblems(
    UC = UC,
)

sequence = SimulationSequence(
    problems = problems,
    intervals = Dict(
        "UC" => (Hour(24), Consecutive()),
    ),
    ini_cond_chronology = IntraProblemChronology(),
);

sim = Simulation(
    name = "test",
    steps = 2,
    problems = problems,
    sequence = sequence,
    simulation_folder = mktempdir(cleanup = true),
)
build_out = build!(sim; serialize = false)
execute_out = execute!(sim)
```

### PR DESCRIPTION
**Pull request by sourabhdalvi**
This change just checks the problem state after the solve it terminated by control parameters like MAXTIME, if the problem is returned in pre-solve state its converted back to the original problem. 

Fixes #133

### CODE REVIEW

File: src/MOI/MOI_wrapper.jl [hunk 1]
```diff
@@ -2350,18 +2350,18 @@ function MOI.optimize!(model::Optimizer)
...
     # 7 Solution in memory is valid.
-    # @show str = bitstring(Int32(state))
-    # @show is_loaded = str[end] == '1'
-    # @show is_lppres = str[end-1] == '1'
-    # @show is_mippre = str[end-2] == '1'
-    # @show is_solava = str[end-7] == '1'
-    # Xpress.postsolve(model.inner) - post solve fails is problem is post solved
+    is_lppres = state & 2^1 > 0
+    is_mippre = state & 2^2 > 0
+    is_solava = state & 2^7 > 0
```
Comment (joaquimg) [inline src/MOI/MOI_wrapper.jl:2361]: Remove this since not used.

**Review by joaquimg — APPROVED** [review]
Nice!
